version: "ipinn"

example:
  name: "Burgers1D"

model:
  model_name: "AttentionNet"
  activation: "tanh"
  init: "Glorot normal"

training:
  trainer_name: "ImprovedTrainer"
  optimizer: "adam"
  lr: 0.001
  iterations: 100
  batch_size: 128
  display_every: 10
  lr_decay_step: 1000
  lr_decay_gamma: 0.9

data:
  num_domain: 10000
  num_boundary: 1000
  num_initial: 500
  num_test: 1000

dims:
  in_dim: 2
  depth: 5
  width: 70
  out_dim: 1

ipinn:
  gamma: 1000.0
  n_samples: 100000
